### ISSUE TITLE
Run de-identification on CelebA-HQ

### ISSUE THREAD

**Issue by CeLuigi** [ldz666666/RiDDLE#12]
Hi,

Thank you for your amazing work. I would like to run de-identification on the CelebA-HQ dataset.
How can I do it? In particular, where can I find the inversion encoder that maps the original image to the latent space?

Thanks a lot.
Cheers,
Luigi

**Comment by DongzeLi-CASIA** [comment]
Hi, please use [e4e](https://github.com/omertov/encoder4editing) to extract latent codes for faces in CelebA-HQ
