### ISSUE TITLE
No pre-trained segmentation model was found.

### ISSUE THREAD

**Issue by Vickie0710** [ldz666666/RiDDLE#5]
Hello! This is really interesting work! I am currently trying to run it, but encountered an issue during inference. It shows that the pre-trained segmentation model "./pretrained_models/79999_iter.pth" is missing or cannot be found ([Errno 2] No such file or directory: './pretrained_models/79999_iter.pth'). Upon checking the provided data and pre-trained model link, I did not find this specific pre-trained model mentioned.

**Comment by Vickie0710** [comment]
This is the error page. 
<img width="483" alt="image" src="https://github.com/ldz666666/RiDDLE/assets/97725167/cdbf656d-cb41-417a-b14b-ae3fc9032bc5">

<img width="569" alt="image" src="https://github.com/ldz666666/RiDDLE/assets/97725167/2941a889-56a4-4828-b618-cc9855a39a81">
This is the corresponding code.

**Comment by DongzeLi-CASIA** [comment]
Hi, the segmentation model weight is actually the 'parsenet.pth' provided in the readme.

**Comment by Vickie0710** [comment]
Thank you very much for your answer! However, I have encountered a new problem, and the error page is as follows:：
<img width="1022" alt="image" src="https://github.com/ldz666666/RiDDLE/assets/97725167/42003e86-1add-4e99-897f-b30289fe9145">

**Comment by DongzeLi-CASIA** [comment]
Maybe you can try the pretrained model in [here](https://github.com/zllrunning/face-parsing.PyTorch) , or delete the face parsing part, it won't affect the inference result.

**Comment by Vickie0710** [comment]
Thank you very much!
It seems that the link you provided cannot be opened.

**Comment by DongzeLi-CASIA** [comment]
> Thank you very much! It seems that the link you provided cannot be opened.

Sorry for the mistake, I have fixed the link, try again？

**Comment by Vickie0710** [comment]
Thank you, this link can be opened now.
