### ISSUE TITLE
About  data

### ISSUE THREAD

**Issue by Vickie0710** [ldz666666/RiDDLE#6]
Hi,I want to know how this embedding(invert_w_256.pt) was obtaine.
<img width="170" alt="image" src="https://github.com/ldz666666/RiDDLE/assets/97725167/19b349fa-022a-4761-b957-f9dc2c9c92f8">

**Comment by DongzeLi-CASIA** [comment]
please refer to [e4e](https://github.com/omertov/encoder4editing)
