### ISSUE TITLE
About Experiments

### ISSUE THREAD

**Issue by zheyuanliu233** [ldz666666/RiDDLE#8]
Hello, I have some questions about Table 3 in the 4.5 Face Utility section of the paper.

The table compares the Bounding box distance and Landmark distance between the encrypted image and the original image. The distance used here is L1 distance or L2 distance, Landmark selects 5 or 68 points, and the distance in the table is the sum of distances or the average result. I did not see any relevant explanation in this paper.

I really hope to receive your answer.

**Comment by DongzeLi-CASIA** [comment]
Hi, please refer to [mtcnn](https://github.com/TropComplique/mtcnn-pytorch), we use 5 points, l1 distance and average result.

**Comment by zheyuanliu233** [comment]
Thanks.

**Comment by zheyuanliu233** [comment]
@ldz666666  In addition, does the resolution of the images has been resized to 256 * 256 before evaluation

> Hi, please refer to [mtcnn](https://github.com/TropComplique/mtcnn-pytorch), we use 5 points, l1 distance and average result.

**Comment by shiyizhiyuanla** [comment]
@ldz666666

**Comment by DongzeLi-CASIA** [comment]
> @ldz666666 In addition, does the resolution of the images has been resized to 256 * 256 before evaluation
> 
> > Hi, please refer to [mtcnn](https://github.com/TropComplique/mtcnn-pytorch), we use 5 points, l1 distance and average result.

Yes, but you may need to resize the image to fit the size of the pretrained model before calculating lpips or landmarks.
