### ISSUE TITLE
Landmark distance reported in the paper

### ISSUE THREAD

**Issue by JhEdLp** [ldz666666/RiDDLE#9]
Hi, 

For the facial landmarks and Bounding box distances reported in **Table 3** of the main paper, the Euclidean norm is used as the distance metric, or another distance. I am trying to replicate these results, but the results obtained are not similar to those reported in the paper. Additionally, for Dlib landmarks uses all 68 points?

**Comment by DongzeLi-CASIA** [comment]
please refer to [issue8](https://github.com/ldz666666/RiDDLE/issues/8)

**Comment by JhEdLp** [comment]
In the isue8, no respond my question, I know that MtCNN return 5 key points, but do you don't specify, if for Dlib results in the Table3, uses all 68 points.
